# Generated by Django 5.2.4 on 2025-07-20 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spend_to_date_daily', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spend_to_date_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_daily_reset', models.DateField(default=django.utils.timezone.now)),
                ('last_monthly_reset', models.DateField(default=django.utils.timezone.now)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget.advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused_by_budget', models.BooleanField(default=False)),
                ('is_paused_by_daypart', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='budget.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Daypart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(max_length=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayparts', to='budget.budget')),
            ],
        ),
        migrations.CreateModel(
            name='SpendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_events', to='budget.campaign')),
            ],
        ),
    ]
